# Lecture 10의 데모

### Lecture 10의 데모에 대한 코드

참고자료: 

https://github.com/data-8/materials-sp22/blob/main/lec/lec15.ipynb

https://github.com/data-8/materials-sp22/blob/main/lec/lec16.ipynb

In [ ]:
import os
from google.colab import drive

drive.mount('/content/gdrive')

%cd /content/gdrive/MyDrive/ITEC419-fa22/lec

Mounted at /content/gdrive
/content/gdrive/MyDrive/ITEC419-fa22/lec

In [ ]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## **Random Sampling**

We load in a dataset of all United domestic flights from 6/1/15 to 8/9/15, their destination and how long they were delayed, in minutes.

In [ ]:
united = Table.read_table('united.csv')
united = united.with_column('Row', np.arange(united.num_rows)).move_to_start('Row')
united

Row  | Date   | Flight Number | Destination | Delay
0    | 6/1/15 | 73            | HNL         | 257
1    | 6/1/15 | 217           | EWR         | 28
2    | 6/1/15 | 237           | STL         | -3
3    | 6/1/15 | 250           | SAN         | 0
4    | 6/1/15 | 267           | PHL         | 64
5    | 6/1/15 | 273           | SEA         | -6
6    | 6/1/15 | 278           | SEA         | -8
7    | 6/1/15 | 292           | EWR         | 12
8    | 6/1/15 | 300           | HNL         | 20
9    | 6/1/15 | 317           | IND         | -10
... (13815 rows omitted)

Some deterministic samples:

A random sample:

## **Distributions**

## **Large Random Samples**

## **Statistics**

In [ ]:
united.show(3)

## **Probability & Empirical Distribution of a Statistic**

### Empirical Distributions of a Statistic (Overlayed)

In [ ]:
sample_medians_10 = make_array()
sample_medians_100 = make_array()
sample_medians_1000 = make_array()

num_simulations = 2000

for i in np.arange(num_simulations):
    new_median_10 = sample_median(10)
    sample_medians_10 = np.append(sample_medians_10, new_median_10)
    new_median_100 = sample_median(100)
    sample_medians_100 = np.append(sample_medians_100, new_median_100)
    new_median_1000 = sample_median(1000)
    sample_medians_1000 = np.append(sample_medians_1000, new_median_1000)

In [ ]:
sample_medians = Table().with_columns('Size 10', sample_medians_10, 
                                      'Size 100', sample_medians_100,
                                      'Size 1000', sample_medians_1000)

In [ ]:
sample_medians.hist(bins = np.arange(-5, 30))

## **Swain vs. Alabama**

In [ ]:
Table().with_column(
    'Number of Black Men on Panel of 100', panels
).hist(bins=np.arange(5.5,40.))

# Plotting details; ignore this code
plots.ylim(-0.002, 0.09)
plots.scatter(8, 0, color='red', s=30);

## **Mendel and Pea Flowers**

In [ ]:
## Mendel had 929 plants, of which 709 had purple flowers